### PR TITLE
Add endpoint for uploading a file

### LINKED ISSUE #2: Submit request
Method is `POST` and url is `/api/job/{appname}` (appname could be haddock3)

With header: `Authorization: <some token>`

Body of request is a multipart form with single file which is an archive with config file and data files.

### PR DESCRIPTION
**Pull request by sverhoeven**
Refs #1
Fixes #2 

This PR also

* Submitting a job requires you pick an application that can run the uploaded archive
* uploading a file will 
  1. Unpack file to job dir and check that config file that application requires is present
  2. Run application in job dir
  3. Update state of job in db
  4. Make stdout of job available as route
* for now the job runs directly without a queue in the background
* job is owned by the submitter, user can only see jobs they submitted
* job keeps track of when it was created and last updated
* Make linter less strict for test code.
* Upgrade GH actions to remove warnings
* Reshuffle readme
* Tests have same directory structure as the thing they test

To test see [example](https://github.com/i-VRESSE/bartender/tree/file-upload#word-count-example)

### CODE REVIEW

**Comment by Peter9192** [comment]
Just a heads up: I managed to setup bartender locally and have it run the wordcount example. Planning to try and test it a bit more next week. 

So far the only issue I encountered was with poetry, same or similar as [reported here](https://github.com/python-poetry/poetry/issues/1917#issuecomment-1235998997). That fix worked for me, but it took some time to figure out as the humongous stack trace was not super helpful.

**Comment by sverhoeven** [comment]
TODO
* in README do alembic before serve

**Review by Peter9192 — APPROVED** [review]
Pair-reviewed! Look super slick 😎

**Comment by sverhoeven** [comment]
Thanks for reviewing

**Pull request merged**
